abilities = {
    "deathblade": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 600,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "cdw": 27000
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "cdw": 16e000
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 600,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "cdw": 24000
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 800,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "cdw": 30000
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "cdw": 25000
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1700,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "cdw": 27000
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 500,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "cdw": 12000
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1000,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "cdw": 24000
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
        },
        {
            "key": "z",
            "abilityType": "specialty1",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 895, "top": 839, "width": 13, "height": 12},
            "directional": True,
        },
    ],
}
